eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
server:
  port: 8090
spring:
  application:
    name: user
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  mongo:
    username: root
    password: root