eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka

server:
  port: 8080
spring:
  application:
    name: post
  config:
    import: optional:configserver:http://localhost:8888
