eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
server:
  port: 8090
spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb+srv://ulvu:pass@cluster0.id9f5gp.mongodb.net/?retryWrites=true&w=majority
      database: mygrocerylist